### ISSUE TITLE
Implement Alert for when Translation package cannot be downloaded

### ISSUE THREAD

**Issue by AbelKel** [AbelKel/Capstone#20]
https://github.com/AbelKel/Capstone/blob/11ac2b6627a4f51cb5572a00b1f17efa6fb4aa3b/Capstone/Translating%20/Translate.m#L70
* Users might encounter errors while downloading translation package. There should be a UI representation such as UIAlert.

**Comment by angelacaq** [comment]
It might be worth to take a look at all places where we check for errors & handle them gracefully (e.g. show a dialog and/or just return without action). We can then clean up the `NSLogs` :)

**Comment by AbelKel** [comment]
I used the null return as an identifier for the existence of an error and basically said if return is null , then the user should check their internet connection and maybe restart the app.

If a better idea comes to mind, I will implement it in the translation error handing branch

**Comment by AbelKel** [comment]
<img width="1746" alt="Screen Shot 2022-08-10 at 3 11 35 PM" src="https://user-images.githubusercontent.com/96321082/184029456-44f6e5ef-9f67-4922-bb54-20c6b9151eb4.png">

This is the current error handling method I am implementing in the accounts view controller. If the translation package is not downloaded, it will not be able to translate the text of "Take Survey Button" to another language. Hence, I'm using the Take Survey Button to detect if there is a translation issue.
